# DS 3000/CS 3200 Lab 1

Due: Tuesday May 13 in-class

### Submission Instructions
Upload this `ipynb` file to GitHub, and then to Gradescope.  To ensure that your submitted `ipynb` file represents your latest code, make sure to give a fresh `Kernel > Restart & Run All` just before uploading the `ipynb` file to GitHub and verify that the correct version is represented on Gradescope.

### Tips for success
- Collaborate: bounce ideas off of each other, if you are having trouble you can ask your classmates or Dr. Gerber for help with specific issues, however...
- [(See)](http://www.northeastern.edu/osccr/academic-integrity), i.e. you are welcome to **talk about/discuss** (*not* show or allow each other to copy your answers to) the problems.

# Part 1 (40 points): Intro to Markdown

Use the markdown language below to create your own brief wikipedia-esque description of a topic related to International Government and Politics. 

Your mini-wiki page must include:
- three headers: a title, subtitle and subsubtitle (the #, ##, ### syntax)
- an embedded image from a web address (use an [image hosting site](https://makeawebsitehub.com/free-photo-hosting/) if you'd like to upload your own)
- a **markdown** table of size at least 9 cells (i.e. 3 by 3, or 5 by 2)
- a list in **markdown**
- a link to another website

To practice typing in math mode, also include a LaTeX formula describing how your final grade is going to be calculated based on the syllabus, something like:

$$grade = weight_1*score_1 + weight_2*score_2$$

Please be **brief** in your text.  Aim for roughly 3 sentences total of text.

# Pain Louvain
## Rumored to be the best student restaurant dining option!
![image](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiSNUFHJ375BBOLH8DvRRUsZXozq9EjbfdyA&s)

### Some Specials
| Sandwich Name  | Protein       | Price|   |   |
|----------------|---------------|------|---|---|
| Pain Louvain   | Ham           | 4,50 |   |   |
| Zalmdelphia    | Smoked Salmon | 4,50 |   |   |
| Smokey Chicken | Chicken       | 4,20 |   |   |

### Facebook page
https://www.instagram.com/painlouvain/?hl=en

$$Final Grade = Test grade_1*score_1 + Final grade_2*score_2 + HW grade*score_3$$

# Part 2: Numpy
## Part 2.1: Creating Arrays (10 points)

Create the following two arrays using the NumPy library and then print them out. Call the first array `array_a` and the second array `array_b` (make sure you keep the `import` statement below):

$$\mathbf{array_a} = \begin{bmatrix}3 & 8 & -2 & 3\\
.5 & -1 & 6 & 4\\
-5 & 7 & -42 & 2
\end{bmatrix}$$

$$\mathbf{array_b} = \begin{bmatrix}42 & 38 & 34\\
30 & 26 & 22\\
18 & 14 & 10\\
6 & 2 & -2\\
-6 & -10 & -14
\end{bmatrix}$$

In [29]:
# make sure to import numpy library
import numpy as np

array_a = np.array([[3, 8, -2, 3],
                   [0.5, -1, 6, 4],
                   [-5, 7, -42, 2]])

array_b = np.array([[42, 38, 34],
                   [30, 26, 22],
                   [18, 14, 10],
                   [6, 2, -2],
                   [-6, -10, -14]])

In [5]:
# uncomment below to print array_a
array_a

array([[  3. ,   8. ,  -2. ,   3. ],
       [  0.5,  -1. ,   6. ,   4. ],
       [ -5. ,   7. , -42. ,   2. ]])

In [6]:
# uncomment below to print array_b
array_b

array([[ 42,  38,  34],
       [ 30,  26,  22],
       [ 18,  14,  10],
       [  6,   2,  -2],
       [ -6, -10, -14]])

## Part 2.2: Exploring Arrays (15 points)

1. Give the shape, size, ndim, and nbytes for each of the two arrays.
1. Take the transpose of both arrays. Call these `t_array_a` and `t_array_b`.
1. Try to add `array_a` and `t_array_b` (*prove* and *show* you did this with commented out code), then remove the last column of `t_array_b` and try to add them again. In a markdown cell, explain what happened.

In [13]:
t_array_a = array_a.T
t_array_b = array_b.T
t_array_b = np.delete(t_array_b, 3, axis=1)
array_a + t_array_b

array([[ 45. ,  38. ,  16. ,  -3. ],
       [ 38.5,  25. ,  20. ,  -6. ],
       [ 29. ,  29. , -32. , -12. ]])

It returned the error ValueError: operands could not be broadcast together with shapes (3,4) (3,5) initially because the shapes are not the same

The shape was the same after the last row was removed, and was able to add the two arrays together.

# Part 3: Pandas
## Part 3.1: Reading in Data (5 points)

On Canvas is the `train_stations_europe.csv` file. It was adapted from [this Kaggle data set](https://www.kaggle.com/datasets/headsortails/train-stations-in-europe). Read this data set in, using the `id` as the index column, and print the first few rows of the data. Make sure you keep the `import` statement below!

In [14]:
# make sure to import pandas library
import pandas as pd

In [16]:
df = pd.read_csv('train_stations_europe.csv', index_col='id')
df.head()

name   latitude  longitude  parent_station_id country  \
id                                                                             
1   Chateau-Arnoux-St-Auban  44.081790   6.001625                NaN      FR   
2   Chateau-Arnoux-St-Auban  44.061565   5.997373                1.0      FR   
3     Chateau-Arnoux Mairie  44.063863   6.011248                1.0      FR   
4           Digne-les-Bains  44.350000   6.350000                NaN      FR   
6           Digne-les-Bains  44.088710   6.222982                4.0      FR   

       time_zone  is_city  is_main_station  is_airport  
id                                                      
1   Europe/Paris     True            False       False  
2   Europe/Paris    False             True       False  
3   Europe/Paris    False            False       False  
4   Europe/Paris     True            False       False  
6   Europe/Paris    False             True       False

## Part 3.2: Manipulating Data (20 points)

1. Create a subset of the data set which (a) **includes** only train stations in Belgium and (b) **excludes** all train stations which are **not** in a city. Make sure to save this subset as a new data frame and print the first few rows of the data.
1. Use the `.describe()` function to produce summary statistics for the subset from the previous part. Create a markdown cell and explain:
    - What Series did the `.describe()` function run on? What Series did it not run on? What is the difference, and what does this mean the `.describe()` function is used for?

In [28]:
isValid = (df.country == 'BE') & (df.is_city == False)
subset = df.loc[isValid]
subset.head()

subset.describe()

latitude     longitude  parent_station_id
count  52548.000000  52548.000000        3849.000000
mean      48.734018      8.312637       16905.449208
std        4.726578      5.103700       11598.005768
min       32.693171    -16.775314           1.000000
25%       46.479283      6.776102        7527.000000
50%       47.360918      8.396244       10781.000000
75%       50.715754     10.771913       28231.000000
max       68.441110     37.897127       67935.000000

In [ ]:
# The function ran on only the numerical Series within this dataset.
# It completely ignored the Series that were either Strings or Booleans.
# This function is used to find information regarding central tendency.

# Part 4: GitHub (10 points)

When you finish the first three parts, give one last restart and run all to this file. Then, go to the [DS 3000 GitHub](https://github.com/eaegerber/ds3000_summer25), fork it and then clone it to your local machine. Then:

- In the forked and cloned ds3000_summer25 repo, make a new branch (`git checkout -b lab-upload`)
- Create a folder with your name (as Dr. Gerber did)
- Navigate to that folder and place this jupyter notebook inside
- Add the file as the change to be committed (`git add .\Lab1_MyName.ipynb`)
- Check `git status`, your changes should be staged
- Commit the changes with a short message (`git commit -m "My message"`)
- Push the repository to GitHub (`git push origin lab-upload`)
- Navigate the the GitHub in the browser and create a pull request
- Once the pull request is merged, you can delete your branch in the "Pull Requests" tab in the browser
- Finally, upload the Lab to Gradescope. When you do so, it will give you the option to do it via GitHub; do that.