# DS 3000/CS 3200 Lab 1

Due: Tuesday May 13 in-class

### Submission Instructions
Upload this `ipynb` file to GitHub, and then to Gradescope.  To ensure that your submitted `ipynb` file represents your latest code, make sure to give a fresh `Kernel > Restart & Run All` just before uploading the `ipynb` file to GitHub and verify that the correct version is represented on Gradescope.

### Tips for success
- Collaborate: bounce ideas off of each other, if you are having trouble you can ask your classmates or Dr. Gerber for help with specific issues, however...
- [(See)](http://www.northeastern.edu/osccr/academic-integrity), i.e. you are welcome to **talk about/discuss** (*not* show or allow each other to copy your answers to) the problems.

# Part 1 (40 points): Intro to Markdown

Use the markdown language below to create your own brief wikipedia-esque description of a topic related to International Government and Politics. 

Your mini-wiki page must include:
- three headers: a title, subtitle and subsubtitle (the #, ##, ### syntax)
- an embedded image from a web address (use an [image hosting site](https://makeawebsitehub.com/free-photo-hosting/) if you'd like to upload your own)
- a **markdown** table of size at least 9 cells (i.e. 3 by 3, or 5 by 2)
- a list in **markdown**
- a link to another website

To practice typing in math mode, also include a LaTeX formula describing how your final grade is going to be calculated based on the syllabus, something like:

$$grade = weight_1*score_1 + weight_2*score_2$$

Please be **brief** in your text.  Aim for roughly 3 sentences total of text.


#international economics
## overview of iternational economics
### interantional economics is a diverse complex topic which encompases the commerce interactions of multiple nations

![image](https://media.wiley.com/product_data/coverImage300/26/11195549/1119554926.jpg)

| trade | exchange rates | currency |   |   |
|-------|----------------|----------|---|---|
| True  | 1:1            | yen      |   |   |
| False | 2:1            | pound    |   |   |
| True  | 3:1            | euro     |   |   |


List of exhange rates compared to the U.S dollar:
1. yen : 164.46
2. lev : 1.9558
3. Pound : 0.84290

This is a link for further information: ![International Economics - Ghent University](https://www.ugent.be/eb/economics/en/research/inttradeinvestmigrpg)

Display Equation: $$ Homework: 40 + Lab: 20 + Quiz1: 20 + Quiz2: 20 $$ 



# Part 2: Numpy
## Part 2.1: Creating Arrays (10 points)

Create the following two arrays using the NumPy library and then print them out. Call the first array `array_a` and the second array `array_b` (make sure you keep the `import` statement below):

$$\mathbf{array_a} = \begin{bmatrix}3 & 8 & -2 & 3\\
.5 & -1 & 6 & 4\\
-5 & 7 & -42 & 2
\end{bmatrix}$$

$$\mathbf{array_b} = \begin{bmatrix}42 & 38 & 34\\
30 & 26 & 22\\
18 & 14 & 10\\
6 & 2 & -2\\
-6 & -10 & -14
\end{bmatrix}$$

In [17]:
# make sure to import numpy library
import numpy as np

In [21]:
array_a = np.array([[3, 8, -2, 3], [.5, -1, 6, 4], [-5, 7, -42, 2]])
array_b = np.array([[42, 38, 34], [30, 26, 22], [18, 14, 10], [6, 2, -2], [-6, -10, -14]])



array([[ 42,  38,  34],
       [ 30,  26,  22],
       [ 18,  14,  10],
       [  6,   2,  -2],
       [ -6, -10, -14]])

In [76]:
# uncomment below to print array_a
array_a

In [23]:
# uncomment below to print array_b
array_b

array([[ 42,  38,  34],
       [ 30,  26,  22],
       [ 18,  14,  10],
       [  6,   2,  -2],
       [ -6, -10, -14]])

## Part 2.2: Exploring Arrays (15 points)

1. Give the shape, size, ndim, and nbytes for each of the two arrays.
1. Take the transpose of both arrays. Call these `t_array_a` and `t_array_b`.
1. Try to add `array_a` and `t_array_b` (*prove* and *show* you did this with commented out code), then remove the last column of `t_array_b` and try to add them again. In a markdown cell, explain what happened.

In [43]:
array_a.shape
array_b.shape
t_array_a = array_a.T
t_array_b = array_b.T
t_array_a.shape
t_array_b.shape
#array_a + t_array_b
# I recieved an error stating the arrays could not be added since they were different shape
t_array_b = np.delete(t_array_b, 3, axis=1)
t_array_b

array([[ 42,  30,  18,  -6],
       [ 38,  26,  14, -10],
       [ 34,  22,  10, -14]])

removing the last column of t_array_b converted it from a (3,5) matrix into a (3,4) matrix

# Part 3: Pandas
## Part 3.1: Reading in Data (5 points)

On Canvas is the `train_stations_europe.csv` file. It was adapted from [this Kaggle data set](https://www.kaggle.com/datasets/headsortails/train-stations-in-europe). Read this data set in, using the `id` as the index column, and print the first few rows of the data. Make sure you keep the `import` statement below!

In [47]:
# make sure to import pandas library
import pandas as pd

In [55]:
df = pd.read_csv('train_stations_europe.csv', encoding='unicode_escape', index_col = 'id')
df.head()

name   latitude  longitude  parent_station_id country  \
id                                                                             
1   Chateau-Arnoux-St-Auban  44.081790   6.001625                NaN      FR   
2   Chateau-Arnoux-St-Auban  44.061565   5.997373                1.0      FR   
3     Chateau-Arnoux Mairie  44.063863   6.011248                1.0      FR   
4           Digne-les-Bains  44.350000   6.350000                NaN      FR   
6           Digne-les-Bains  44.088710   6.222982                4.0      FR   

       time_zone  is_city  is_main_station  is_airport  
id                                                      
1   Europe/Paris     True            False       False  
2   Europe/Paris    False             True       False  
3   Europe/Paris    False            False       False  
4   Europe/Paris     True            False       False  
6   Europe/Paris    False             True       False

## Part 3.2: Manipulating Data (20 points)

1. Create a subset of the data set which (a) **includes** only train stations in Belgium and (b) **excludes** all train stations which are **not** in a city. Make sure to save this subset as a new data frame and print the first few rows of the data.
1. Use the `.describe()` function to produce summary statistics for the subset from the previous part. Create a markdown cell and explain:
    - What Series did the `.describe()` function run on? What Series did it not run on? What is the difference, and what does this mean the `.describe()` function is used for?

In [63]:
belgium = (df.country == 'BE') & (df.is_city == False)
subset = df.loc[belgium]
subset




name   latitude  longitude  \
id                                                             
1121                 Tournai Frontiere        NaN        NaN   
1122                         Froyennes        NaN        NaN   
1313                          Mouscron        NaN        NaN   
1354                   Quevy Frontiere        NaN        NaN   
5893                    Bruxelles-Midi  50.835374   4.335695   
...                                ...        ...        ...   
23235                        Poperinge  50.854449   2.736343   
29230  Liege-Guillemins (Busparkplatz)  50.624150   5.568310   
37401                          Arcades  50.809722   4.398333   
61114                       Anderlecht  50.817900   4.291800   
61121                Charleroi Airport  50.470350   4.471349   

       parent_station_id country        time_zone  is_city  is_main_station  \
id                                                                            
1121                 NaN      BE  Europe/Brussels    False            False   
1122                 NaN      BE  Europe/Brussels    False            False   
1313                 NaN      BE  Europe/Brussels    False            False   
1354              6003.0      BE  Europe/Brussels    False            False   
5893              5974.0      BE  Europe/Brussels    False             True   
...                  ...     ...              ...      ...              ...   
23235                NaN      BE  Europe/Brussels    False            False   
29230             5995.0      BE  Europe/Brussels    False            False   
37401                NaN      BE  Europe/Brussels    False            False   
61114                NaN      BE  Europe/Brussels    False            False   
61121                NaN      BE  Europe/Brussels    False            False   

       is_airport  
id                 
1121        False  
1122        False  
1313        False  
1354        False  
5893        False  
...           ...  
23235       False  
29230       False  
37401       False  
61114       False  
61121        True  

[573 rows x 9 columns]

# Part 4: GitHub (10 points)

When you finish the first three parts, give one last restart and run all to this file. Then, go to the [DS 3000 GitHub](https://github.com/eaegerber/ds3000_summer25), fork it and then clone it to your local machine. Then:

- In the forked and cloned ds3000_summer25 repo, make a new branch (`git checkout -b lab-upload`)
- Create a folder with your name (as Dr. Gerber did)
- Navigate to that folder and place this jupyter notebook inside
- Add the file as the change to be committed (`git add .\Lab1_MyName.ipynb`)
- Check `git status`, your changes should be staged
- Commit the changes with a short message (`git commit -m "My message"`)
- Push the repository to GitHub (`git push origin lab-upload`)
- Navigate the the GitHub in the browser and create a pull request
- Once the pull request is merged, you can delete your branch in the "Pull Requests" tab in the browser
- Finally, upload the Lab to Gradescope. When you do so, it will give you the option to do it via GitHub; do that.